---

- name: Install Nginx
  apt: name=nginx update_cache={{ update_apt_cache }} state=installed
  tags: packages

- name: Add the nginx user to the application group
  user: name=nginx groups={{ gunicorn_group }} append=yes

- name: Ensure that a strong Diffie-Hellman group is used
  command: openssl dhparam -out /etc/ssl/certs/dhparams.pem 2048 creates=/etc/ssl/certs/dhparams.pem
  when: nginx_strong_dh_group is defined and nginx_strong_dh_group and nginx_use_letsencrypt

- name: Create the Nginx configuration file
  template: src=nginx_settings.j2
            dest=/etc/nginx/sites-available/minedash
  notify: reload nginx

- name: Setup minedash nginx logrotate
  template: src=minedash_nginx_logrotate.j2
            dest=/etc/logrotate.d/minedash-nginx

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/minedash
        dest=/etc/nginx/sites-enabled/minedash
        state=link
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
