---

- name: Provision a Minecraft server on a Vagrant box
  hosts: all
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - "{{ env }}"

  roles:
    - base
    - minecraft
    - db
    - web
    - backups
    - nginx
