---

- name: drop in additional mods
  when: additional_mods is defined and additional_mods
  copy:
    src: "{{ item.src }}"
    dest: "{{ minecraft_server_folder }}/config/{{ item.dest }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0644
  with_items: "{{ additional_mods }}"
