---

- name: ensure group access to whitelist.json
  file:
    path: "{{ minecraft_whitelist_file }}"
    state: touch

- name: Ensure that the minecraft file permissions are set properly
  file: path={{ minecraft_server_folder }}
        recurse=yes
        owner={{ minecraft_user }}
        group={{ minecraft_group }}
        state=directory
        mode=0774
