---

- name: Create the Supervisor config file
  template: src=supervisor_config.j2
            dest=/etc/supervisor/conf.d/minedash.conf

- name: Setup minedash logrotate
  template: src=minedash_logrotate.j2
            dest=/etc/logrotate.d/minedash

- name: Re-read the Supervisor config files
  supervisorctl: name=minedash state=present

- name: Restart Supervisor
  supervisorctl: name=minedash state=restarted
