---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Create the minedash settings file
  template: src=minedash_settings.j2
            dest={{ settings_file_path }}
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
  tags: deploy

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
  when: run_django_collectstatic is defined and run_django_collectstatic
  tags: django.collectstatic
