---

- name: Setup the Git repo
  git: repo={{ minedash_git_repo }}
       version={{ minedash_git_branch }}
       dest={{ project_path }}
       accept_hostkey=yes
  tags: git

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  tags: git
